# This file was generated by GoReleaser. DO NOT EDIT.
class Dots < Formula
  desc "Delivery tool for dotfiles"
  homepage "https://github.com/mitinarseny/dots"
  url "https://github.com/mitinarseny/dots/releases/download/v0.1.3/dots_0.1.3_Darwin_x86_64.tar.gz"
  version "0.1.3"
  sha256 "8b43b749ebbc111cfac39d11c00314c0b0abc3f4c15db9ebdf92f1be6937f99b"

  def install
    bin.install "dots"
  end
end
